### ISSUE TITLE
Built-in caching

### ISSUE THREAD

**Issue by shawon1fb** [lucidfy/lucid#11]
gorvel should have an Built-in caching system
 
- In memory cache
- Radis cache

**Comment by daison12006013** [comment]
Right, do you mind to initialize this? I might be starting with the authentication over `Request`, then `Mailer` on the next one.

**Comment by shawon1fb** [comment]
I might need your Consultancy.

**Comment by daison12006013** [comment]
@shawon1fb, I like the way you implemented the `storage`, probably implement the same thing for cache
just that avoid initializing the driver on runtime, better to only initialize it when the http request was called "if necessary"

https://github.com/daison12006013/gorvel/commit/47f097e819d0be95e8753d488bb5578140293882#diff-28e83abaa8dc05966b8f279604889cc2ef579f9ff0a0d73d29aa2b80e7bc1837R49

I'll make a discord channel for us to discuss this, as of the moment it's 2:43am in my country right now 😅

**Comment by daison12006013** [comment]
Caching using File is now added

```go
ca := cache.File() // or cache.Store("file") for future switchable caching
ca.Put("hello", "world")
```

Test samples can be seen here [pkg/facade/cache/file_test.go](https://github.com/lucidfy/lucid/blob/develop/pkg/facade/cache/file_test.go)
